// ============================================
// נתוני Mock למצב פיתוח ללא Supabase
// ============================================
// כשה-.env מכיל placeholders, ה-API מחזיר את הנתונים האלה.
// זה מאפשר לבנות את ה-frontend בלי להמתין ל-credentials.
// כשתעבור לחיבור אמיתי, הנתונים יילקחו מ-Supabase.
// ============================================

export const mockProducts = [
  {
    id: 'mock-001', handle: 'glow-rainbow-5-dark', sku: 'GR5-DARK',
    name: 'Glow Rainbow #5 Dark', description: 'פילמנט סילק עם אפקט קשת זוהר בחושך',
    type: 'silk', color: 'Rainbow Dark', color_hex: null,
    weight_grams: 1000, diameter: '1.75mm',
    price: 98, compare_at_price: null, stock: 0,
    image_url: 'https://shop.briner.co.il/cdn/shop/files/glowrainbowdark.png?v=1779016083&width=533',
    badge: 'חדש', is_active: true, is_featured: true, sort_order: 1,
  },
  {
    id: 'mock-002', handle: 'silk-bicolor-blue-green', sku: 'SBI-BG',
    name: 'Silk Bicolor - Blue Green', description: 'פילמנט סילק דו-צבעי כחול-ירוק',
    type: 'silk', color: 'Blue/Green', color_hex: null,
    weight_grams: 1000, diameter: '1.75mm',
    price: 98, compare_at_price: null, stock: 25,
    image_url: 'https://shop.briner.co.il/cdn/shop/files/blue_green.png?v=1778656563&width=533',
    badge: null, is_active: true, is_featured: false, sort_order: 2,
  },
  {
    id: 'mock-003', handle: 'silk-bicolor-purple-blue', sku: 'SBI-PB',
    name: 'Silk Bicolor - Purple Blue', description: 'פילמנט סילק דו-צבעי סגול-כחול',
    type: 'silk', color: 'Purple/Blue', color_hex: null,
    weight_grams: 1000, diameter: '1.75mm',
    price: 79, compare_at_price: 98, stock: 30,
    image_url: 'https://shop.briner.co.il/cdn/shop/files/purpleblue.png?v=1779018797&width=533',
    badge: 'מבצע', is_active: true, is_featured: false, sort_order: 3,
  },
  {
    id: 'mock-004', handle: 'silk-bicolor-red-gold', sku: 'SBI-RG',
    name: 'Silk Bicolor - Red Gold', description: 'פילמנט סילק דו-צבעי אדום-זהב',
    type: 'silk', color: 'Red/Gold', color_hex: null,
    weight_grams: 1000, diameter: '1.75mm',
    price: 79, compare_at_price: 98, stock: 18,
    image_url: 'https://shop.briner.co.il/cdn/shop/files/Redgold.png?v=1779018405&width=533',
    badge: 'מבצע', is_active: true, is_featured: false, sort_order: 4,
  },
  {
    id: 'mock-005', handle: 'pla-rainbow', sku: 'PLA-RNB',
    name: 'PLA - Rainbow', description: 'פילמנט PLA צבעוני - קשת',
    type: 'silk', color: 'Rainbow', color_hex: null,
    weight_grams: 1000, diameter: '1.75mm',
    price: 79, compare_at_price: null, stock: 40,
    image_url: 'https://shop.briner.co.il/cdn/shop/files/rainbow.png?v=1779013356&width=533',
    badge: 'פופולרי', is_active: true, is_featured: true, sort_order: 5,
  },
  {
    id: 'mock-006', handle: 'pla-red', sku: 'PLA-RED',
    name: 'PLA - אדום', description: 'פילמנט PLA סטנדרטי בצבע אדום',
    type: 'pla', color: 'אדום', color_hex: '#D32F2F',
    weight_grams: 1000, diameter: '1.75mm',
    price: 69, compare_at_price: null, stock: 50,
    image_url: 'https://shop.briner.co.il/cdn/shop/files/red.png?v=1778659909&width=533',
    badge: null, is_active: true, is_featured: false, sort_order: 10,
  },
  {
    id: 'mock-007', handle: 'pla-blue', sku: 'PLA-BLU',
    name: 'PLA - כחול', description: 'פילמנט PLA סטנדרטי בצבע כחול',
    type: 'pla', color: 'כחול', color_hex: '#1976D2',
    weight_grams: 1000, diameter: '1.75mm',
    price: 69, compare_at_price: null, stock: 50,
    image_url: 'https://shop.briner.co.il/cdn/shop/files/blue.png?v=1778664859&width=533',
    badge: null, is_active: true, is_featured: false, sort_order: 11,
  },
  {
    id: 'mock-008', handle: 'pla-white', sku: 'PLA-WHT',
    name: 'PLA - לבן', description: 'פילמנט PLA סטנדרטי בצבע לבן',
    type: 'pla', color: 'לבן', color_hex: '#FFFFFF',
    weight_grams: 1000, diameter: '1.75mm',
    price: 69, compare_at_price: null, stock: 60,
    image_url: 'https://shop.briner.co.il/cdn/shop/files/white.png?v=1778656559&width=533',
    badge: null, is_active: true, is_featured: true, sort_order: 12,
  },
  {
    id: 'mock-009', handle: 'pla-yellow', sku: 'PLA-YEL',
    name: 'PLA - צהוב', description: 'פילמנט PLA סטנדרטי בצבע צהוב',
    type: 'pla', color: 'צהוב', color_hex: '#FBC02D',
    weight_grams: 1000, diameter: '1.75mm',
    price: 69, compare_at_price: null, stock: 35,
    image_url: 'https://shop.briner.co.il/cdn/shop/files/yellow.png?v=1778661626&width=533',
    badge: null, is_active: true, is_featured: false, sort_order: 13,
  },
  {
    id: 'mock-010', handle: 'pla-green-dark', sku: 'PLA-GRN-D',
    name: 'PLA - ירוק כהה', description: 'פילמנט PLA סטנדרטי בצבע ירוק כהה',
    type: 'pla', color: 'ירוק כהה', color_hex: '#2E7D32',
    weight_grams: 1000, diameter: '1.75mm',
    price: 69, compare_at_price: null, stock: 25,
    image_url: 'https://shop.briner.co.il/cdn/shop/files/dark_green.png?v=1778656564&width=533',
    badge: null, is_active: true, is_featured: false, sort_order: 14,
  },
  {
    id: 'mock-011', handle: 'pla-orange', sku: 'PLA-ORG',
    name: 'PLA - כתום', description: 'פילמנט PLA סטנדרטי בצבע כתום',
    type: 'pla', color: 'כתום', color_hex: '#F57C00',
    weight_grams: 1000, diameter: '1.75mm',
    price: 69, compare_at_price: null, stock: 22,
    image_url: 'https://shop.briner.co.il/cdn/shop/files/orange.png?v=1778660877&width=533',
    badge: null, is_active: true, is_featured: false, sort_order: 15,
  },
  {
    id: 'mock-012', handle: 'pla-purple', sku: 'PLA-PUR',
    name: 'PLA - סגול', description: 'פילמנט PLA סטנדרטי בצבע סגול',
    type: 'pla', color: 'סגול', color_hex: '#7B1FA2',
    weight_grams: 1000, diameter: '1.75mm',
    price: 69, compare_at_price: null, stock: 28,
    image_url: 'https://shop.briner.co.il/cdn/shop/files/purple.png?v=1778661329&width=533',
    badge: null, is_active: true, is_featured: false, sort_order: 16,
  },
  // ---- מוצרי silk נוספים ----
  {
    id: 'mock-013', handle: 'silk-bicolor-red-black', sku: 'SBI-RB',
    name: 'Silk Bicolor - Red Black', description: 'פילמנט סילק דו-צבעי אדום-שחור',
    type: 'silk', color: 'Red/Black', color_hex: null,
    weight_grams: 1000, diameter: '1.75mm', price: 98, compare_at_price: null, stock: 20,
    image_url: 'https://shop.briner.co.il/cdn/shop/files/red_black.png?v=1778656567&width=533',
    badge: null, is_active: true, is_featured: false, sort_order: 20,
  },
  {
    id: 'mock-014', handle: 'silk-bicolor-red-blue', sku: 'SBI-RBL',
    name: 'Silk Bicolor - Red Blue', description: 'פילמנט סילק דו-צבעי אדום-כחול',
    type: 'silk', color: 'Red/Blue', color_hex: null,
    weight_grams: 1000, diameter: '1.75mm', price: 98, compare_at_price: null, stock: 18,
    image_url: 'https://shop.briner.co.il/cdn/shop/files/blue_red.png?v=1778656566&width=533',
    badge: null, is_active: true, is_featured: false, sort_order: 21,
  },
  {
    id: 'mock-015', handle: 'silk-bicolor-red-green', sku: 'SBI-RG2',
    name: 'Silk Bicolor - Red Green', description: 'פילמנט סילק דו-צבעי אדום-ירוק',
    type: 'silk', color: 'Red/Green', color_hex: null,
    weight_grams: 1000, diameter: '1.75mm', price: 98, compare_at_price: null, stock: 22,
    image_url: 'https://shop.briner.co.il/cdn/shop/files/red_green.png?v=1778656566&width=533',
    badge: null, is_active: true, is_featured: false, sort_order: 22,
  },
  {
    id: 'mock-016', handle: 'silk-bicolor-black-purple', sku: 'SBI-BP',
    name: 'Silk Bicolor - Black Purple', description: 'פילמנט סילק דו-צבעי שחור-סגול',
    type: 'silk', color: 'Black/Purple', color_hex: null,
    weight_grams: 1000, diameter: '1.75mm', price: 98, compare_at_price: null, stock: 15,
    image_url: 'https://shop.briner.co.il/cdn/shop/files/purple_black.png?v=1778656562&width=533',
    badge: null, is_active: true, is_featured: false, sort_order: 23,
  },
  {
    id: 'mock-017', handle: 'silk-bicolor-purple-gold', sku: 'SBI-PG',
    name: 'Silk Bicolor - Purple Gold', description: 'פילמנט סילק דו-צבעי סגול-זהב',
    type: 'silk', color: 'Purple/Gold', color_hex: null,
    weight_grams: 1000, diameter: '1.75mm', price: 98, compare_at_price: null, stock: 12,
    image_url: 'https://shop.briner.co.il/cdn/shop/files/purple_gold.png?v=1778656565&width=533',
    badge: null, is_active: true, is_featured: false, sort_order: 24,
  },
  {
    id: 'mock-018', handle: 'silk-bicolor-yellow-green', sku: 'SBI-YG',
    name: 'Silk Bicolor - Yellow Green', description: 'פילמנט סילק דו-צבעי צהוב-ירוק',
    type: 'silk', color: 'Yellow/Green', color_hex: null,
    weight_grams: 1000, diameter: '1.75mm', price: 98, compare_at_price: null, stock: 24,
    image_url: 'https://shop.briner.co.il/cdn/shop/files/yellowgreen.png?v=1778665330&width=533',
    badge: null, is_active: true, is_featured: false, sort_order: 25,
  },
  // ---- מוצרי PLA נוספים ----
  {
    id: 'mock-019', handle: 'pla-gray', sku: 'PLA-GRY',
    name: 'PLA - אפור', description: 'פילמנט PLA סטנדרטי בצבע אפור',
    type: 'pla', color: 'אפור', color_hex: '#757575',
    weight_grams: 1000, diameter: '1.75mm', price: 69, compare_at_price: null, stock: 30,
    image_url: 'https://shop.briner.co.il/cdn/shop/files/gray.png?v=1778656563&width=533',
    badge: null, is_active: true, is_featured: false, sort_order: 30,
  },
  {
    id: 'mock-020', handle: 'pla-pink', sku: 'PLA-PNK',
    name: 'PLA - ורוד', description: 'פילמנט PLA סטנדרטי בצבע ורוד',
    type: 'pla', color: 'ורוד', color_hex: '#EC407A',
    weight_grams: 1000, diameter: '1.75mm', price: 69, compare_at_price: null, stock: 25,
    image_url: 'https://shop.briner.co.il/cdn/shop/files/pink.png?v=1778660947&width=533',
    badge: null, is_active: true, is_featured: false, sort_order: 31,
  },
  {
    id: 'mock-021', handle: 'pla-brown', sku: 'PLA-BRN',
    name: 'PLA - חום', description: 'פילמנט PLA סטנדרטי בצבע חום',
    type: 'pla', color: 'חום', color_hex: '#6D4C41',
    weight_grams: 1000, diameter: '1.75mm', price: 69, compare_at_price: null, stock: 18,
    image_url: 'https://shop.briner.co.il/cdn/shop/files/brown.png?v=1778660649&width=533',
    badge: null, is_active: true, is_featured: false, sort_order: 32,
  },
  {
    id: 'mock-022', handle: 'pla-green-light', sku: 'PLA-GRN-L',
    name: 'PLA - ירוק בהיר', description: 'פילמנט PLA סטנדרטי בצבע ירוק בהיר',
    type: 'pla', color: 'ירוק בהיר', color_hex: '#81C784',
    weight_grams: 1000, diameter: '1.75mm', price: 69, compare_at_price: null, stock: 22,
    image_url: 'https://shop.briner.co.il/cdn/shop/files/light_green.png?v=1778656566&width=533',
    badge: null, is_active: true, is_featured: false, sort_order: 33,
  },
  {
    id: 'mock-023', handle: 'pla-blue-light', sku: 'PLA-BLU-L',
    name: 'PLA - כחול בהיר', description: 'פילמנט PLA סטנדרטי בצבע כחול בהיר',
    type: 'pla', color: 'כחול בהיר', color_hex: '#64B5F6',
    weight_grams: 1000, diameter: '1.75mm', price: 69, compare_at_price: null, stock: 26,
    image_url: 'https://shop.briner.co.il/cdn/shop/files/light_blue.png?v=1778656567&width=533',
    badge: null, is_active: true, is_featured: false, sort_order: 34,
  },
  {
    id: 'mock-024', handle: 'pla-skin', sku: 'PLA-SKN',
    name: 'PLA - צבע עור', description: 'פילמנט PLA סטנדרטי בצבע עור',
    type: 'pla', color: 'צבע עור', color_hex: '#FFCC80',
    weight_grams: 1000, diameter: '1.75mm', price: 69, compare_at_price: null, stock: 20,
    image_url: 'https://shop.briner.co.il/cdn/shop/files/skin.png?v=1778659848&width=533',
    badge: null, is_active: true, is_featured: false, sort_order: 35,
  },
];
